import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: ["js/**/*.js", "tests/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        performance: "readonly",
        crypto: "readonly",
        structuredClone: "readonly",
        navigator: "readonly",
        // Chrome extension API
        chrome: "readonly",
        // Cross-file globals (js/*.js loaded via <script> tags in dependency order)
        // constants.js
        SYNC_KEY: "readonly",
        SYNC_CORE_KEY: "readonly",
        SYNC_INDEX_KEY: "readonly",
        SYNC_LINKS_PREFIX: "readonly",
        SYNC_QUOTES_PREFIX: "readonly",
        SYNC_BACKGROUNDS_PREFIX: "readonly",
        SYNC_TEST_KEY: "readonly",
        LOCAL_ASSETS_KEY: "readonly",
        LEGACY_KEY: "readonly",
        SYNC_META_KEY: "readonly",
        FAVICON_CACHE_KEY: "readonly",
        BACKGROUND_THUMBS_KEY: "readonly",
        DEFAULT_LINK_SECTION: "readonly",
        NEW_SECTION_OPTION: "readonly",
        SYNC_CHUNK_CHAR_TARGET: "readonly",
        SYNC_TOTAL_QUOTA_BYTES: "readonly",
        SYNC_PER_ITEM_LIMIT: "readonly",
        SYNC_VERSION: "readonly",
        V2_META_KEY: "readonly",
        V2_CHUNK_PREFIX: "readonly",
        V2_TMP_META_KEY: "readonly",
        V2_TMP_CHUNK_PREFIX: "readonly",
        fallbackConfig: "readonly",
        // utils.js
        hashString: "readonly",
        padChunkIndex: "readonly",
        chunkStringBySize: "readonly",
        buildV2ChunkKeys: "readonly",
        calculatePayloadBytes: "readonly",
        isDataUrl: "readonly",
        ensureLinkIds: "readonly",
        createId: "readonly",
        timeAgo: "readonly",
        rand: "readonly",
        shuffleArray: "readonly",
        boostColor: "readonly",
        safeParseUrl: "readonly",
        blobToDataUrl: "readonly",
        fileToDataUrl: "readonly",
        createImageThumbnail: "readonly",
        // storage.js
        storageLocal: "readonly",
        storageSync: "readonly",
        shouldUseSimSync: "readonly",
        getSimSyncStore: "readonly",
        validateSimSyncSnapshot: "readonly",
        applySimFault: "readonly",
        loadConfig: "readonly",
        loadDefaultConfig: "readonly",
        loadSyncConfigCore: "readonly",
        loadV2SyncConfig: "readonly",
        loadChunkedSyncConfig: "readonly",
        saveSyncConfigV2: "readonly",
        setSyncConfig: "readonly",
        clearSyncStorage: "readonly",
        collectChunks: "readonly",
        getChunkKeys: "readonly",
        preflightV2Payload: "readonly",
        estimateSyncUsage: "readonly",
        getConfigSizeBytes: "readonly",
        setSyncStatus: "readonly",
        updateSyncUsage: "readonly",
        refreshSyncStatus: "readonly",
        runSyncQuotaTest: "readonly",
        cleanupTempV2Keys: "readonly",
        // config.js (will be extracted in phase 4)
        mergeConfig: "readonly",
        splitConfig: "readonly",
        applyLocalAssets: "readonly",
        mergeLocalAssets: "readonly",
        normalizeQuotesImport: "readonly",
        deriveSections: "readonly",
        collectConfigFromEditors: "readonly",
        collectLinks: "readonly",
        collectSectionsFromEditor: "readonly",
        collectSectionsFromMain: "readonly",
        collectCollapsedSectionsFromMain: "readonly",
        collectLinksFromMain: "readonly",
        collectBackgrounds: "readonly",
        collectQuotes: "readonly",
        collectSearch: "readonly",
        collectLayout: "readonly",
        collectVisibility: "readonly",
        collectPrivacy: "readonly",
        collectBranding: "readonly",
        collectBackgroundMode: "readonly",
        // customize.js (will be extracted in phase 6)
        setupSettings: "readonly",
        setupSettingsNav: "readonly",
        renderSettings: "readonly",
        renderLinksEditor: "readonly",
        renderQuotesEditor: "readonly",
        renderBackgroundsEditor: "readonly",
        renderSearchEditor: "readonly",
        renderBackgroundModeEditor: "readonly",
        renderBrandingEditor: "readonly",
        renderLayoutEditor: "readonly",
        updateLayoutControlState: "readonly",
        renderVisibilityEditor: "readonly",
        renderPrivacyEditor: "readonly",
        addLinkRow: "readonly",
        addBackgroundRow: "readonly",
        addEngineRow: "readonly",
        refreshDefaultEngineOptions: "readonly",
        refreshLinkSectionChoices: "readonly",
        getLinkRowSectionValue: "readonly",
        setLinkRowSectionValue: "readonly",
        moveLinkRowToSection: "readonly",
        handleLinkSectionSelection: "readonly",
        finalizeCustomLinkSection: "readonly",
        getDefaultLinkSectionFromMain: "readonly",
        ensureLinksSection: "readonly",
        createLinksSection: "readonly",
        setRearrangeMode: "readonly",
        updateLinkRowDragState: "readonly",
        updateEngineRowDragState: "readonly",
        updateMainDragState: "readonly",
        findReorderTarget: "readonly",
        ensureBackgroundPreviewObserver: "readonly",
        queueBackgroundPreview: "readonly",
        getBackgroundThumb: "readonly",
        getBackgroundThumbKey: "readonly",
        updateFileLabel: "readonly",
        // render.js (will be extracted in phase 5)
        renderAll: "readonly",
        renderSections: "readonly",
        renderQuote: "readonly",
        renderBackground: "readonly",
        renderImageBackground: "readonly",
        renderBranding: "readonly",
        renderSearch: "readonly",
        applyVisibility: "readonly",
        updatePageLayout: "readonly",
        updateGridColumns: "readonly",
        setupGridObserver: "readonly",
        resolveFavicon: "readonly",
        fetchFavicon: "readonly",
        applyGradientMode: "readonly",
        applySignatureGradient: "readonly",
        applySodaGradient: "readonly",
        applyGithubDarkGradient: "readonly",
        applyAzureGradient: "readonly",
        applyDraculaGradient: "readonly",
        applySynthwaveGradient: "readonly",
        applyDaylightGradient: "readonly",
        setAuraPalette: "readonly",
        sampleDominantColor: "readonly",
        collectFaviconSources: "readonly",
        // init.js globals (mutable shared state, will be extracted in phase 7)
        activeConfig: "writable",
        faviconCache: "writable",
        backgroundThumbs: "writable",
        isRearranging: "writable",
        lastRenderLinks: "writable",
        gridObserver: "writable",
        currentDragType: "writable",
        currentDragSection: "writable",
        backgroundPreviewObserver: "writable",
        backgroundPreviewPanel: "writable",
        canRearrangeEditor: "writable",
      },
    },
    rules: {
      // Align with CONTRIBUTING.md coding standards
      "no-var": "error",
      "prefer-const": "warn",
      eqeqeq: ["error", "always"],
      "no-empty-catch": "off",
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // constants.js declares globals consumed by other js/*.js files
    // Module files that declare globals consumed by other js/*.js files
    files: ["js/constants.js", "js/utils.js", "js/storage.js", "js/config.js", "js/render.js", "js/customize.js", "js/init.js"],
    rules: {
      "no-unused-vars": "off",
      "no-redeclare": "off",
    },
  },
  {
    // Test files and helpers use ES modules (vitest)
    files: ["tests/**/*.test.js", "tests/helpers/**/*.js"],
    languageOptions: {
      sourceType: "module",
    },
  },
  {
    ignores: ["node_modules/", "dist/", "tests/storage-harness*.js"],
  },
];
